# Generated by Django 3.2 on 2022-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUsuario',
            fields=[
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('id', models.UUIDField()),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('fecha_registro', models.DateTimeField()),
                ('nro_cliente', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_usuario',
                'managed': False,
            },
        ),
    ]
