
"""
ENDPOINTS POSIBLES:
LISTAR MEDICIONES ACORDE A UN RANGO DE FECHAS
LISTAR MEDICIONES SEGUN FECHA

LISTAR CONSUMOS EN EL MES POR DIA
LISTAR CONSUMOS ENTRE FECHAS POR DIA

OBTENER CONSUMO DEL DIA DE UN EQUIPO
OBTENER CONSUMO DEL MES DE UN EQUIPO
OBTENER CONSUMO ANUAL DE UN EQUIPO

"""

from django.urls import path


urlpatterns = [

]
