# Generated by Django 3.2 on 2022-12-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de gateway', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo_gateway',
                'verbose_name_plural': 'tipo_gateways',
            },
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la consola', max_length=255, null=True, verbose_name='nombre')),
                ('base_url', models.CharField(help_text='base de url', max_length=255, verbose_name='base_url')),
                ('apikey', models.CharField(help_text='APIKEY', max_length=255, verbose_name='apikey')),
                ('tipo_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_gateway.tipogateway')),
            ],
            options={
                'verbose_name': 'consola',
                'verbose_name_plural': 'consolas',
            },
        ),
    ]
