# Generated by Django 3.2 on 2022-11-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de gateway', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo_gateway',
                'verbose_name_plural': 'tipo_gateways',
            },
        ),
    ]
