# Generated by Django 3.2 on 2022-11-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(help_text='base de url', max_length=255, verbose_name='base_url')),
                ('apikey', models.CharField(help_text='APIKEY', max_length=255, verbose_name='apikey')),
                ('tipo_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_gateway.tipogateway')),
            ],
            options={
                'verbose_name': 'consola',
                'verbose_name_plural': 'consolas',
            },
        ),
    ]
