# Generated by Django 3.2 on 2022-10-25 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la entidad', max_length=255, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=False, help_text='Es una entidad activa?', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'entidad',
                'verbose_name_plural': 'entidades',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, help_text='fecha de asignación del miembro a entidad', verbose_name='fecha de asignación')),
                ('activo', models.BooleanField(default=False, help_text='Es un miembro activo?', verbose_name='activo')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'MONITOR')], help_text='Indica el Rol de un Miembro en la Entidad', verbose_name='rol')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.entidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'miembro',
                'verbose_name_plural': 'miembros',
            },
        ),
    ]
