# Generated by Django 3.2 on 2022-11-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('nro_serie', models.CharField(help_text='Nro. de serie del equipo', max_length=255, primary_key=True, serialize=False, verbose_name='equipo')),
                ('label', models.CharField(help_text='Nombre de la etiqueta', max_length=255, null=True, verbose_name='etiqueta')),
                ('name', models.CharField(help_text='Nombre del equipo asignado', max_length=255, verbose_name='nombre')),
                ('latitud', models.DecimalField(decimal_places=6, help_text='latitud', max_digits=8, null=True, verbose_name='latitud')),
                ('longitud', models.DecimalField(decimal_places=6, help_text='longitud', max_digits=9, null=True, verbose_name='longitud')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, help_text='fecha de asignación del equipo', verbose_name='fecha de asignación')),
                ('activo', models.BooleanField(default=False, help_text='equipo activo?', verbose_name='activo')),
                ('app_eui', models.CharField(default='', help_text='APPEUI de credencial', max_length=255, null=True, verbose_name='APPEUI')),
                ('app_key', models.CharField(default='', help_text='APPKEY de credencial', max_length=255, null=True, verbose_name='APPKEY')),
                ('dev_eui', models.CharField(default='', help_text='DEVEUI de credencial', max_length=255, null=True, verbose_name='DEVEUI')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
            },
        ),
    ]
