# Generated by Django 3.2 on 2022-12-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correo', '0001_initial'),
        ('entidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailservice',
            name='id_entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.entidad'),
        ),
    ]
