# Generated by Django 3.2 on 2022-11-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cliente', models.IntegerField()),
                ('nro_suministro', models.IntegerField()),
                ('nro_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
            options={
                'verbose_name': 'medidor',
                'verbose_name_plural': 'medidores',
                'db_table': 'medidor',
            },
        ),
    ]
