# Generated by Django 3.2 on 2022-12-20 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cliente', models.UUIDField(default=uuid.uuid4, help_text='Número de Cliente', null=True, verbose_name='Nro. Cliente')),
                ('nro_suministro', models.IntegerField(help_text='Número de suministro', null=True, verbose_name='Nro. suministro')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, help_text='fecha de asignación del medidor', verbose_name='fecha de asignación')),
                ('equipo', models.ForeignKey(help_text='Equipo', on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'medidor',
                'verbose_name_plural': 'medidores',
                'db_table': 'medidor',
                'unique_together': {('nro_cliente', 'nro_suministro', 'equipo')},
            },
        ),
    ]
