# Generated by Django 3.2 on 2022-12-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
        ('medidor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medidor',
            unique_together={('nro_cliente', 'nro_suministro', 'equipo')},
        ),
    ]
