# Generated by Django 3.2 on 2022-12-01 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medidor', '0002_alter_medidor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='nro_cliente',
            field=models.UUIDField(default=uuid.uuid4, help_text='Número de Cliente', null=True, verbose_name='Nro. Cliente'),
        ),
    ]
